Repository AllAlgorithms/c, pull requests merged in 2020-10, with the labels that each got.

#37 Matrix multiplication and execution time recording
  math/Matrix Multiplication/matmul.c
Labels: needs test

#178 Prims Algorithm
  Prims.c
  searching/Jump Search
Labels: hacktober-accepted

#183 Create binarytree.c
  tree/binarytree.c
Labels: hacktober-accepted

#181 Added bitonic_sort.
  algoritms/sorting/bitonic_sort.c
Labels: hacktober-accepted

#197 Adding Comments
  algorithms/dynamic-programming/lis.c
Labels: hacktober-accepted

#196 Addition of ploynomial using Linklist
  algorithms/data-structures/Add_Ploynomial_Linklist.c
Labels: hacktober-accepted

#195 Adding 2 more important algorithms
  algorithms/N-Queen.c
  algorithms/PRIMS.C
Labels: hacktober-accepted

#198 Added pigeonhole-sort
  algorithms/sorting/pigeonhole_sort.c
Labels: hacktober-accepted

#199 Added DFS
  algorithms/graphs/DFS.c
Labels: hacktober-accepted

#223 Add stack implementation using single link list in c language to data structure.
  algorithms/data-structures/StackImplementationUsingSingSingleLinkeList.c
Labels: hacktober-accepted, on hold
